### ISSUE TITLE
Blog Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#247]
# Directions:
 
Take the code of [this](https://github.com/smaranjitghose/my_blog) repo, do the changes and give the PR to a branch ``test`` for this repo. [ The test branch should only contain code for the blog page]

# Tasks: 
- [ ] Add Dark Mode
- [ ] Modify Footer as per our current website 
- [ ] Modify Navbar as per our current website
- [ ] Improve the UI of the landing page of the blog with content and Illustrations 

# Pre-requisites:

Please have a look at how Jekyll works before you do the changes

**Comment by iamkrati22** [comment]
Hey, I would like to work on the issue as a part of Nwoc. Can you assign this to me? I am not familiar with jekyll but willing to learn.

**Comment by smaranjitghose** [comment]
> Hey, I would like to work on the issue as a part of Nwoc. Can you assign this to me? I am not familiar with jekyll but willing to learn.

Sure!

You can make use of [this](https://devhints.io/jekyll) cheatsheet if you wish to get started with Jekyll

**Comment by sammy8825** [comment]
hello @smaranjitghose  can u assign me this issue but I don't know Jekyll? But I'm very much interested to learn it.

**Comment by smaranjitghose** [comment]
> hello @smaranjitghose can u assign me this issue but I don't know Jekyll? But I'm very much interested to learn it.

Sure

**Comment by sammy8825** [comment]
@smaranjitghose is there any channel where we can ask doubts ?

**Comment by smaranjitghose** [comment]
> @smaranjitghose is there any channel where we can ask doubts ?

Yes, it's [here](https://join.slack.com/t/nwoc-workspace/shared_invite/zt-ju5z8s6r-u04wP4SJ69kXEy2fz~AuZg)

**Comment by Ayushgup85** [comment]
is this issue still open?

**Comment by Vishal-raj-1** [comment]
@smaranjitghose Sir I am looking forward to this issue. will do this issue, could you please add DWOC & SWOC label.

**Comment by Abhijay007** [comment]
@smaranjitghose sir I made something like this  for the blog landing page

***demo***
![demo-blog](https://user-images.githubusercontent.com/64387054/103292248-76a08f00-4a13-11eb-81af-69c9f5d31bb0.gif)

@smaranjitghose can I work on this ? can you please assign me this.

**Comment by smaranjitghose** [comment]
> @smaranjitghose sir I made something like this for the blog landing page
> 
> _**demo**_
> ![demo-blog](https://user-images.githubusercontent.com/64387054/103292248-76a08f00-4a13-11eb-81af-69c9f5d31bb0.gif)
> 
> @smaranjitghose can I work on this ? can you please assign me this.

Actually, we are using fastpages keeping in mind that in the future, we can simply drag and drop jupyter notebooks for writing blogs

**Comment by smaranjitghose** [comment]
> @smaranjitghose Sir I am looking forward to this issue. will do this issue, could you please add DWOC & SWOC label.

Sure. Have a look at Jekyll first and then move to fastpages

**Comment by Vishal-raj-1** [comment]
> Sure. Have a look at Jekyll first and then move to fastpages
 Okay !!

**Comment by Pranjal-2001** [comment]
Can you please assign it to me?

**Comment by smaranjitghose** [comment]
> Can you please assign it to me?

Sure. I am assigning this to you for a week. Please do read the description above. ( We don't want to build a separate blog page😊. Rather build upon fastpages itself]

**Comment by nilisha-jais** [comment]
I want to work on this issue as a part of SWoC2021

**Comment by Vishal-raj-1** [comment]
I am working on it. Will send the PR for the same !!

**Comment by smaranjitghose** [comment]
> I want to work on this issue as a part of SWoC2021

You can work on it in parallel. Have a look at the codebase of fastpages
